### ISSUE TITLE
OpenEye tests are failing

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#167]
I've finally restored the OpenEye tests and it looks like we're now failing with some SQM failures:
```
Running: /home/travis/miniconda/envs/_test/bin/../bin/sqm -O -i sqm.in -o sqm.out
Error: cannot run "/home/travis/miniconda/envs/_test/bin/../bin/sqm -O -i sqm.in -o sqm.out" of bcc() in charge.c properly, exit
```
Full traceback:
```
======================================================================
ERROR: Testing molecule benzene
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/openmoltools-0.6.9-py2.7.egg/openmoltools/tests/test_common_molecules.py", line 42, in <lambda>
    yield utils.tag_description(lambda : utils.test_molecule('molecule', tripos_mol2_filename), "Testing molecule %s" % molecule_name)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/openmoltools-0.6.9-py2.7.egg/openmoltools/utils.py", line 285, in test_molecule
    (gaff_mol2_filename, frcmod_filename) = amber.run_antechamber(molecule_name, tripos_mol2_filename, charge_method=charge_method)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/openmoltools-0.6.9-py2.7.egg/openmoltools/amber.py", line 356, in run_antechamber
    shutil.copy( 'out.mol2', gaff_mol2_filename )
  File "/home/travis/miniconda/envs/_test/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'out.mol2'
-------------------- >> begin captured logging << --------------------
openmoltools.openeye: DEBUG: benzene
openmoltools.amber: DEBUG: antechamber -i in.mol2 -fi mol2 -o out.mol2 -fo mol2 -s 2 -c bcc
openmoltools.amber: DEBUG: Running: /home/travis/miniconda/envs/_test/bin/../bin/bondtype -j full -i ANTECHAMBER_BOND_TYPE.AC0 -o ANTECHAMBER_BOND_TYPE.AC -f ac
Running: /home/travis/miniconda/envs/_test/bin/../bin/atomtype -i ANTECHAMBER_AC.AC0 -o ANTECHAMBER_AC.AC -p gaff
Total number of electrons: 42; net charge: 0
Running: /home/travis/miniconda/envs/_test/bin/../bin/sqm -O -i sqm.in -o sqm.out
Error: cannot run "/home/travis/miniconda/envs/_test/bin/../bin/sqm -O -i sqm.in -o sqm.out" of bcc() in charge.c properly, exit
openmoltools.amber: DEBUG: parmchk2 -i out.mol2 -f mol2 -o out.frcmod
openmoltools.amber: DEBUG: Cannot open file out.mol2 to read in rmol2(), exit
```

**Comment by jchodera** [comment]
Starting to debug in https://github.com/choderalab/openmoltools/pull/168

**Comment by jchodera** [comment]
Turns out there's lots of broken shit.

**Comment by jchodera** [comment]
Fixed.
