### ISSUE TITLE
Packmol error

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#223]
@davidlmobley, can you take a look at [this failing test](https://travis-ci.org/choderalab/openmoltools/jobs/133226140#L2781-L2795) in `packmol` on `master`?
```
=====================================================================
ERROR: test_packmol.test_packmol_simulation_ternary_bydensity
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/openmoltools-0.7.1.dev0-py2.7.egg/openmoltools/tests/test_packmol.py", line 88, in test_packmol_simulation_ternary_bydensity
    simulation.step(25)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 198, in _simulate
    self.integrator.step(stepsToGo)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 4796, in step
    return _openmm.LangevinIntegrator_step(self, steps)
Exception: Particle coordinate is nan
```

**Comment by davidlmobley** [comment]
Yes, though it will take me til early this afternoon at least - I'm tied up
this morning running job interviews.

On Fri, May 27, 2016 at 5:32 AM, John Chodera <notifications@github.com>
wrote:

> @davidlmobley <https://github.com/davidlmobley>, can you take a look at this
> failing test
> <https://travis-ci.org/choderalab/openmoltools/jobs/133226140#L2781-L2795>
> in packmol on master?
>
> =====================================================================
> ERROR: test_packmol.test_packmol_simulation_ternary_bydensity
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
>     self.test(*self.arg)
>   File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/openmoltools-0.7.1.dev0-py2.7.egg/openmoltools/tests/test_packmol.py", line 88, in test_packmol_simulation_ternary_bydensity
>     simulation.step(25)
>   File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 132, in step
>     self._simulate(endStep=self.currentStep+steps)
>   File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 198, in _simulate
>     self.integrator.step(stepsToGo)
>   File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 4796, in step
>     return _openmm.LangevinIntegrator_step(self, steps)
> Exception: Particle coordinate is nan
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/223>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AGzUYZRDG60u6WwRm0xKKV2vbf3Ym1cYks5qFuRFgaJpZM4IodMe>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
So far, failing to replicate on my machine. Investigating whether it is an issue with openmm-dev, perhaps an API change there or something.

**Comment by davidlmobley** [comment]
I can't replicate so far, even using `openmm-dev`. However, it does not seem to be an issue with `packmol` in that nothing has changed on that front, and it is still working fine elsewhere, so I'm suspecting OpenMM issues. 

@pgrinaway @andrrizzi @juliebehr , any ideas how to troubleshoot when I can't replicate a failure on my own machine? (And can you see if running these tests fails for you?)

**Comment by davidlmobley** [comment]
This is because of no minimization prior to simulation, it seems.
