### ISSUE TITLE
A failure in FreeSolv

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#60]
Are you sure you tested `gaff2xml` on the whole FreeSolv database?  And on the Tripos files?

I am seeing a failure here on 1-ethyl-4-methyl-benzene:
```
  1-ethyl-4-methyl-benzene
LOG: antechamber -i molecule.tripos.mol2 -fi mol2 -o molecule.gaff.mol2 -fo mol2 -s 2 -c bcc -nc 0
LOG: Running: /Users/choderaj/code/amber/amber12/bin/bondtype -j full -i ANTECHAMBER_BOND_TYPE.AC0 -o ANTECHAMBER_BOND_TYPE.AC -f ac

Running: /Users/choderaj/code/amber/amber12/bin/atomtype -i ANTECHAMBER_AC.AC0 -o ANTECHAMBER_AC.AC -p gaff
Total number of electrons: 66; net charge: 0

Running: /Users/choderaj/code/amber/amber12/bin/sqm -O -i sqm.in -o sqm.out
Error: cannot run "/Users/choderaj/code/amber/amber12/bin/sqm -O -i sqm.in -o sqm.out" of bcc() in charge.c properly, exit
```

**Comment by davidlmobley** [comment]
Has this issue moved anywhere? Should my group troubleshoot?

**Comment by kyleabeauchamp** [comment]
I will add to this an additional failure to charge properly, detailed below.

```
======================================================================
ERROR: Testing drugs ZINC03871612
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kyleb/opt/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/kyleb/opt/lib/python2.7/site-packages/openmoltools-0.6.5.dev0-py2.7.egg/openmoltools/tests/test_drugs.py", line 29, in <lambda>
    yield utils.tag_description(lambda : utils.test_molecule(molecule_name, tripos_mol2_filename), "Testing drugs %s" % molecule_name)
  File "/home/kyleb/opt/lib/python2.7/site-packages/openmoltools-0.6.5.dev0-py2.7.egg/openmoltools/utils.py", line 325, in test_molecule
    simulation_ffxml = create_ffxml_simulation(molecule_name, gaff_mol2_filename, frcmod_filename)
  File "/home/kyleb/opt/lib/python2.7/site-packages/openmoltools-0.6.5.dev0-py2.7.egg/openmoltools/utils.py", line 244, in create_ffxml_simulation
    parser.parse_filenames([GAFF_DAT_FILENAME, gaff_mol2_filename, frcmod_filename])
  File "/home/kyleb/opt/lib/python2.7/site-packages/openmoltools-0.6.5.dev0-py2.7.egg/openmoltools/amber_parser.py", line 483, in parse_filenames
    self.process_mol2_file(inputfile)
  File "/home/kyleb/opt/lib/python2.7/site-packages/openmoltools-0.6.5.dev0-py2.7.egg/openmoltools/amber_parser.py", line 126, in process_mol2_file
    atoms, bonds = md.formats.mol2.mol2_to_dataframes(inputfile)
  File "/home/kyleb/opt/lib/python2.7/site-packages/mdtraj-1.4.0.dev0-py2.7-linux-x86_64.egg/mdtraj/formats/mol2.py", line 152, in mol2_to_dataframes
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: 'ZINC03871612.gaff.mol2'
-------------------- >> begin captured logging << --------------------
openmoltools.openeye: DEBUG: ZINC03871612
openmoltools.utils: DEBUG: antechamber -i ZINC03871612.tripos.mol2 -fi mol2 -o ZINC03871612.gaff.mol2 -fo mol2 -s 2 -c bcc
openmoltools.utils: DEBUG: Running: /home/kyleb/opt/bin/../bin/bondtype -j full -i ANTECHAMBER_BOND_TYPE.AC0 -o ANTECHAMBER_BOND_TYPE.AC -f ac

Running: /home/kyleb/opt/bin/../bin/atomtype -i ANTECHAMBER_AC.AC0 -o ANTECHAMBER_AC.AC -p gaff
Total number of electrons: 260; net charge: -4

Running: /home/kyleb/opt/bin/../bin/sqm -O -i sqm.in -o sqm.out
Error: cannot run "/home/kyleb/opt/bin/../bin/sqm -O -i sqm.in -o sqm.out" of bcc() in charge.c properly, exit
openmoltools.utils: DEBUG: parmchk2 -i ZINC03871612.gaff.mol2 -f mol2 -o ZINC03871612.frcmod
openmoltools.utils: DEBUG: Cannot open file ZINC03871612.gaff.mol2 to read in rmol2(), exit
```
```

I personally don't think we need to debug this issue right now because our current recommended charging scheme is via OpenEye.  All of the problems in this issue are related to antechamber charging.

**Comment by jchodera** [comment]
This problem needs to be fixed by parsing the antechamber output for errors
and throwing an appropriate exception for the error. The current scheme
just gives a file not found exception, which is not useful.

We should raise an issue that this needs to be done at some point but don't
need to address this now.

**Comment by davidlmobley** [comment]
Ah, yes. I didn't notice at first glance that this was an antechamber charging issue. I agree that we don't need to fix it for now; we should just close this issue and place specific examples into a new issue which suggests parsing antechamber output for errors.

Somewhat relatedly - if you guys want to give me write access to the repository, I'm happy to help with labeling issues to prioritize, closing issues, etc. Currently I can't do anything of the sort so I just have to comment. :) On the other hand I'm also OK if you prefer to keep all of that work in house - I just need to know what you want.

**Comment by kyleabeauchamp** [comment]
You should now have write access, so you should be able to help us triage issues.

**Comment by jchodera** [comment]
> Ah, yes. I didn't notice at first glance that this was an antechamber charging issue. 

That's because we are not checking the antechamber output for errors, so the error that is raised has no bearing on what the actual error is.  

I think we should, at the very least, put this in a try...except block and raise some sort of exception that the whole process failed for an unknown reason.

**Comment by davidlmobley** [comment]
See also #39 . I'll mark this and #39 closed and start a separate issue for exception handling/Antechamber output parsing as an enhancement.
