### ISSUE TITLE
Errors with gaff2xml.utils.create_ffxml_file()

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#75]
I'm trying to debug the yank [`systembuilder.py`](https://github.com/choderalab/yank/blob/master/yank/systembuilder.py), and am running into this with the doctests (see below).

I think there are a number of (possibly irrelevant) warnings, but any ideas what these exceptions mean?
```
[LSKI1497:~/code/yank/yank.jchodera] choderaj% python -m doctest yank/systembuilder.py
/Users/choderaj/anaconda/lib/python2.7/site-packages/pandas/io/parsers.py:639: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators; you can avoid this warning by specifying engine='python'.
  ParserWarning)
/Users/choderaj/code/yank/install/lib/python2.7/site-packages/mdtraj-0.9.1-py2.7-macosx-10.5-x86_64.egg/mdtraj/formats/mol2.py:94: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  atoms_mdtraj["serial"] = atoms.index
/Users/choderaj/code/yank/install/lib/python2.7/site-packages/mdtraj-0.9.1-py2.7-macosx-10.5-x86_64.egg/mdtraj/formats/mol2.py:98: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  atoms_mdtraj["element"] = atoms.atype.map(gaff_elements)  # IF this is a GAFF mol2, this line should work without issues
/Users/choderaj/code/yank/install/lib/python2.7/site-packages/mdtraj-0.9.1-py2.7-macosx-10.5-x86_64.egg/mdtraj/formats/mol2.py:100: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  atoms_mdtraj["element"] = atoms.atype.apply(lambda x: x.strip(".")[0])  # If this is a sybyl mol2, I think this works generally.
/Users/choderaj/code/yank/install/lib/python2.7/site-packages/mdtraj-0.9.1-py2.7-macosx-10.5-x86_64.egg/mdtraj/formats/mol2.py:102: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  atoms_mdtraj["resSeq"] = np.ones(len(atoms), 'int')
/Users/choderaj/code/yank/install/lib/python2.7/site-packages/mdtraj-0.9.1-py2.7-macosx-10.5-x86_64.egg/mdtraj/formats/mol2.py:103: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  atoms_mdtraj["chainID"] = np.ones(len(atoms), 'int')
LOG: antechamber -i tripos.mol2 -fi mol2 -o MOL.gaff.mol2 -fo mol2 -s 2 -c bcc
LOG: 
Running: /Users/choderaj/anaconda/bin/../bin/atomtype -f ac -p bcc -o ANTECHAMBER_AM1BCC.AC -i ANTECHAMBER_AM1BCC_PRE.AC
Running: /Users/choderaj/anaconda/bin/../bin/bondtype -j full -i ANTECHAMBER_BOND_TYPE.AC0 -o ANTECHAMBER_BOND_TYPE.AC -f ac

Running: /Users/choderaj/anaconda/bin/../bin/atomtype -i ANTECHAMBER_AC.AC0 -o ANTECHAMBER_AC.AC -p gaff
Total number of electrons: 58; net charge: 0

Running: /Users/choderaj/anaconda/bin/../bin/sqm -O -i sqm.in -o sqm.out

Running: /Users/choderaj/anaconda/bin/../bin/am1bcc -i ANTECHAMBER_AM1BCC_PRE.AC -o ANTECHAMBER_AM1BCC.AC -f ac -p /Users/choderaj/anaconda/bin/../dat/antechamber/BCCPARM.DAT -s 2 -j 1

LOG: parmchk2 -i MOL.gaff.mol2 -f mol2 -o MOL.frcmod
LOG: 
**********************************************************************
File "yank/systembuilder.py", line 993, in systembuilder.ComplexSystemBuilder.__init__
Failed example:
    ligand = Mol2SystemBuilder(ligand_mol2_filename, charge=0)
Exception raised:
    Traceback (most recent call last):
      File "/Users/choderaj/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest systembuilder.ComplexSystemBuilder.__init__[4]>", line 1, in <module>
        ligand = Mol2SystemBuilder(ligand_mol2_filename, charge=0)
      File "yank/systembuilder.py", line 956, in __init__
        super(Mol2SystemBuilder, self).__init__(molecule, **kwargs)
      File "yank/systembuilder.py", line 438, in __init__
        self._parameterize_with_gaff2xml(molecule, parameterize_arguments)
      File "yank/systembuilder.py", line 485, in _parameterize_with_gaff2xml
        gaff2xml.utils.create_ffxml_file(gaff_mol2_filename, gaff_frcmod_filename, ffxml_filename)
      File "/Users/choderaj/anaconda/lib/python2.7/site-packages/gaff2xml/utils.py", line 198, in create_ffxml_file
        parser.parse_filenames(filenames)
      File "/Users/choderaj/anaconda/lib/python2.7/site-packages/gaff2xml/amber_parser.py", line 485, in parse_filenames
        self.process_frc_file(inputfile)
      File "/Users/choderaj/anaconda/lib/python2.7/site-packages/gaff2xml/amber_parser.py", line 298, in process_frc_file
        for line in open(inputfile):
    IOError: [Errno 2] No such file or directory: 'M'
**********************************************************************
```

**Comment by davidlmobley** [comment]
Is this still an issue?

**Comment by davidlmobley** [comment]
Closing for now, re-open if needed later.
