### ISSUE TITLE
Fix OEMol / OEGraphMol issue

### ISSUE THREAD

**Issue by kyleabeauchamp** [choderalab/openmoltools#79]
So somewhere we are passing an OEGraphMol when we need a three-dimensional OEMol, leading to the following test failure:

```
kyleb@kyleb-DX4870:~$ nosetests gaff2xml -v
Failure: AttributeError ('OEGraphMol' object has no attribute 'GetConfs') ... ERROR
Failure: AttributeError ('OEGraphMol' object has no attribute 'GetConfs') ... ERROR
Testing drugs molecule_0 with charge method bcc ... ^C
======================================================================
ERROR: Failure: AttributeError ('OEGraphMol' object has no attribute 'GetConfs')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kyleb/opt/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/home/kyleb/opt/lib/python2.7/site-packages/gaff2xml-0.1-py2.7.egg/gaff2xml/tests/test_drugs.py", line 26, in test_drugs
    molecule_name, tripos_mol2_filename = utils.molecule_to_mol2(molecule)
  File "/home/kyleb/opt/lib/python2.7/site-packages/gaff2xml-0.1-py2.7.egg/gaff2xml/utils.py", line 418, in molecule_to_mol2
    return gaff2xml.openeye.molecule_to_mol2(*args, **kwargs)
  File "/home/kyleb/opt/lib/python2.7/site-packages/gaff2xml-0.1-py2.7.egg/gaff2xml/openeye.py", line 253, in molecule_to_mol2
    for k, mol in enumerate(molecule.GetConfs()):
AttributeError: 'OEGraphMol' object has no attribute 'GetConfs'
-------------------- >> begin captured logging << --------------------
gaff2xml.openeye: DEBUG: ZINC03873936
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: AttributeError ('OEGraphMol' object has no attribute 'GetConfs')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kyleb/opt/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/home/kyleb/opt/lib/python2.7/site-packages/gaff2xml-0.1-py2.7.egg/gaff2xml/tests/test_drugs.py", line 36, in test_drug
    molecule_name, tripos_mol2_filename = utils.molecule_to_mol2(molecule)
  File "/home/kyleb/opt/lib/python2.7/site-packages/gaff2xml-0.1-py2.7.egg/gaff2xml/utils.py", line 418, in molecule_to_mol2
    return gaff2xml.openeye.molecule_to_mol2(*args, **kwargs)
  File "/home/kyleb/opt/lib/python2.7/site-packages/gaff2xml-0.1-py2.7.egg/gaff2xml/openeye.py", line 253, in molecule_to_mol2
    for k, mol in enumerate(molecule.GetConfs()):
AttributeError: 'OEGraphMol' object has no attribute 'GetConfs'
-------------------- >> begin captured logging << --------------------
gaff2xml.openeye: DEBUG: ZINC03873936
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 3 tests in 1.921s
```

**Comment by davidlmobley** [comment]
I just ran into this issue too (trying to start using gaff2xml in order to hopefully increase overlap between what my lab is doing and what you are doing). Is there a fix in the works? Should I try and fix it? My recollection is that an OEGraphMol is by necessity single conformation so it has no function GetConfs.

**Comment by kyleabeauchamp** [comment]
What are you specifically trying to do?

**Comment by kyleabeauchamp** [comment]
E.g. if this is FreeSolv related, I have a script here (https://github.com/choderalab/gbff/blob/master/code/rebuild_freesolv.py) that does a lot of the things we might want to do...

**Comment by davidlmobley** [comment]
Just run the tests, at this point. :) Non-critical, but I assumed initially
(until I read this) that I should be concerned if the tests can't run
without error.

On Tue, Apr 28, 2015 at 5:32 PM, Kyle Beauchamp <notifications@github.com>
wrote:

> What are you specifically trying to do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/gaff2xml/issues/79#issuecomment-97271881>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
Yes, I just found that. And I'm about to e-mail to kick off a somewhat
larger discussion.

On Tue, Apr 28, 2015 at 5:33 PM, Kyle Beauchamp <notifications@github.com>
wrote:

> E.g. if this is FreeSolv related, I have a script here (
> https://github.com/choderalab/gbff/blob/master/code/rebuild_freesolv.py)
> that does a lot of the things we might want to do...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/gaff2xml/issues/79#issuecomment-97272036>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
Did you want us to look into this issue? (i.e. ideally the tests should run without error.)

**Comment by kyleabeauchamp** [comment]
#101 might be the answer here, testing this overnight.

**Comment by davidlmobley** [comment]
I still have the same issue running the nose tests on 0.6.5 which I just installed via conda. ("Failure: AttributeError ('OEGraphMol' object has no attribute 'GetConfs') ... ERROR") This is for 2-acetoxybenzoic acid.

**Comment by kyleabeauchamp** [comment]
What version of OpenEye are you using?  I wonder if there's a difference between the versions.

**Comment by davidlmobley** [comment]
Ah, it could be. I am in OEChem 20150211 (I did not upgrade to the latest
beta yet). What are you using?

Thanks.


On Thu, Apr 30, 2015 at 3:36 PM, Kyle Beauchamp <notifications@github.com>
wrote:

> What version of OpenEye are you using? I wonder if there's a difference
> between the versions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/79#issuecomment-97990600>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by kyleabeauchamp** [comment]
OpenEye-python2.7-ubuntu-14.04-x64-2015.2.3.tar.gz

**Comment by davidlmobley** [comment]
Hmm, mine was installed via pip:  pip install -i
https://pypi.binstar.org/openeye/simple openeye

DM


On Thu, Apr 30, 2015 at 4:03 PM, Kyle Beauchamp <notifications@github.com>
wrote:

> OpenEye-python2.7-ubuntu-14.04-x64-2015.2.3.tar.gz
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/79#issuecomment-97995207>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by kyleabeauchamp** [comment]
FWIW, here is the output on my machine:

```
nosetests openmoltools -v --exe

[...]

Testing molecule benzene ... ok
Testing molecule toluene ... ok
Testing molecule phenol ... ok
Testing molecule benzene-1,2-diol ... ok
Testing molecule 2-acetoxybenzoic acid ... ok
Testing drugs ZINC03873936 ... ok
Testing drugs ZINC19632834 ... ok
Testing drugs ZINC03647770 ... ok
Testing drugs ZINC03815424 ... ok
[...]
```

**Comment by davidlmobley** [comment]
Any chance you want to try this out with one of the pip/conda-installable
OpenEye versions? I'd just as soon NOT go back to the "dark ages" way of
installing just to see if it will work for me if I do. The alternative is
to see if it breaks for you if you use the newer way of installing.

On Thu, Apr 30, 2015 at 4:21 PM, Kyle Beauchamp <notifications@github.com>
wrote:

> FWIW, here is the output on my machine:
>
> nosetests openmoltools -v --exe
>
> [...]
>
> Testing molecule benzene ... ok
> Testing molecule toluene ... ok
> Testing molecule phenol ... ok
> Testing molecule benzene-1,2-diol ... ok
> Testing molecule 2-acetoxybenzoic acid ... ok
> Testing drugs ZINC03873936 ... ok
> Testing drugs ZINC19632834 ... ok
> Testing drugs ZINC03647770 ... ok
> Testing drugs ZINC03815424 ... ok
> [...]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/79#issuecomment-97998036>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by kyleabeauchamp** [comment]
Sure, I will try out the pip version

**Comment by jchodera** [comment]
I can also take a stab at getting this to work on travis.  We got info from
OpenEye on how to get this to work by grabbing the license file via HTTP.
I think we just have to host our group license file somewhere that isn't
google indexed or linked to.

--
John D. Chodera
Assistant Faculty Member, Computational Biology
Memorial Sloan-Kettering Cancer Center
email: j <choderaj@mskcc.org>ohn.chodera@choderalab.org
office: 646.888.3400
fax: 510.280.3760
mobile: 415.867.7384
url: http://www.choderalab.org

**Comment by jchodera** [comment]
Actually, that seems insufficiently insecure.  Will consult with OpenEye
further.

**Comment by davidlmobley** [comment]
Yes, I can't imagine how you could get that to work without making the URL
of your license file public. It may require them rethinking how they handle
licensing to a limited extent (i.e. maybe they can allow X number of OE
tool calls without a license within 24 hours?).

David


On Fri, May 1, 2015 at 9:11 AM, John Chodera <notifications@github.com>
wrote:

> Actually, that seems insufficiently insecure. Will consult with OpenEye
> further.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/openmoltools/issues/79#issuecomment-98167999>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436
