### ISSUE TITLE
Fails for catechol?

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmoltools#83]
This seems to fail:
```python
import gaff2xml.openeye
import simtk.openmm as mm
from simtk.openmm import app

iupac_name = 'catechol'
molecule = gaff2xml.openeye.iupac_to_oemol(iupac_name)
import openeye.oeomega as om
omega = om.OEOmega()
omega.SetMaxConfs(1)
omega(molecule)
trajs, ffxmls = gaff2xml.openeye.oemols_to_ffxml([molecule])
ff = app.ForceField(ffxmls)
topology = trajs[0].top.to_openmm()
system = ff.createSystem(topology) 
```

```
[LSKI1497:~/projects/expanded-ensembles] choderaj% python create_relative_transformation.py
LOG: benzene-1,2-diol
LOG: methoxymethylbenzene
/Users/choderaj/projects/expanded-ensembles
LOG: benzene-1,2-diol
LOG: antechamber -i ./lig-0-0.mol2 -fi mol2 -o lig-0-0.gaff.mol2 -fo mol2 -s 2
LOG: Running: /Users/choderaj/anaconda/bin/../bin/bondtype -j full -i ANTECHAMBER_BOND_TYPE.AC0 -o ANTECHAMBER_BOND_TYPE.AC -f ac

Running: /Users/choderaj/anaconda/bin/../bin/atomtype -i ANTECHAMBER_AC.AC0 -o ANTECHAMBER_AC.AC -p gaff

LOG: parmchk2 -i lig-0-0.gaff.mol2 -f mol2 -o lig-0-0.frcmod
LOG: 
Traceback (most recent call last):
  File "create_relative_transformation.py", line 680, in <module>
    [system1, topology1, positions1] = generate_openmm_system(molecule1)
  File "create_relative_transformation.py", line 20, in generate_openmm_system
    system = ff.createSystem(topology)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 519, in createSystem
    force.createForce(sys, data, nonbondedMethod, nonbondedCutoff, args)
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 1174, in createForce
    raise ValueError('No nonbonded parameters defined for atom type '+t)
ValueError: No nonbonded parameters defined for atom type lig-0-H5
```

**Comment by jchodera** [comment]
Actually, this is failing for a lot of molecules (e.g. `aspirin`).  Debugging....

**Comment by jchodera** [comment]
See #85 which tries to test this.

**Comment by davidlmobley** [comment]
I think this is closed now? (I read through the discussion and yes, in general you want to avoid using molecule names for *anything* in the file system. It's not just spaces, but also commas, square brackets, etc which can cause problems - sometimes in the file system, sometimes in external libraries, etc. It's a huge nightmare. I think this is one reason why compound databases typically assign some sort of numerical compound identifier (ZINC, PubChem, etc.).

**Comment by davidlmobley** [comment]
@jchodera , is this something which currently needs resolution? I believe @kyleabeauchamp indicated this is not currently part of your workflow(s)?

**Comment by davidlmobley** [comment]
Closing for now; re-open if this is needed later.
